# DEPLOYMENT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: sample-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      name: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: restqa/sample-project_1-api-gateway
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always

# SERVICE
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: api-gateway
  namespace: sample-project
  name: api-gateway
spec:
  #type: ClusterIP
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
