version: '3'
services:
  api-gateway:
    build: 
      context: ./api-gateway
    ports:
    - "8000:80"
    links:
    - "users:users.sample-project-olivierodo.svc.cluster.local"
    - "addresses:addresses.sample-project-olivierodo.svc.cluster.local"
  users:
    build: ./microservice-users
  addresses:
    build: ./microservice-addresses
    links:
    - "users:users.sample-project-olivierodo.svc.cluster.local"
    environment:
      - URL_USER_SVC=http://users.sample-project-olivierodo.svc.cluster.local:8080


