---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users
  name: users
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: users
      name: users
    spec:
      containers:
      - name: users
        imagePullPolicy: Always
        image: restqa/sample-project_microservice-users
        env:
          - name: PORT
            value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
             cpu: 100m
             memory: 256Mi
          requests:
             cpu: 100m
             memory: 100Mi
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: users
  name: users
spec:
  selector:
    app: users
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

