name: RestQapi - End 2 End

on: [push]

jobs:
  E2E:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-env: [KINTOHUB, UAT]
    steps:
    - uses: actions/checkout@v2
    - name: Run E2E Test Automation on the Environment ${{ matrix.test-env }}
      uses: docker://restqa/restqapi
      env:
        RESTQA_ENV: ${{ matrix.test-env }}
