on: [push]

name: Sample-project-deploy

jobs:
  Build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - api-gateway
          - microservice-users
          - microservice-addresses
    steps:
    - uses: actions/checkout@v2
    - uses: okteto/actions/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: "Activate Namespace"
      uses: okteto/actions/namespace@master
      with:
        namespace: sample-project-olivierodo
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: restqa/sample-project_${{ matrix.component }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        auto_tag: true
        workdir: project/${{ matrix.component }}
    - name: "Deploy"
      uses: okteto/actions/deploy@master
      with:
        namespace: sample-project-olivierodo
        manifest: ./project/${{ matrix.component }}/manifest.yml
        tag: ${{ matrix.component }}:${{ github.sha }}
        registry: registry.cloud.okteto.net
  E2E:
    needs: Build-deploy
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run E2E Test Automation on the Environment ${{ matrix.test-env }}
      uses: docker://restqa/restqa:0.0.1
      with:
        args: restqa run ./tests
      env:
        RESTQA_ENV: okteto
        API_KEY: default-api-key
